version: '3.8'

services:
  webapp:
    volumes:
      - /var/www/audiofiles:/audiofiles
      - /var/www/images:/images
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"
